app:
  allow-get-customers: ${customers.allow-get-customers}

spring:
  application:
    name: customers
  profiles:
    active: production

feign:
  hystrix:
    enabled: false

accounts:
  ribbon:
    listOfServers: http://localhost:7777
    eureka:
      enabled: false

info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
server:
  port: 8887
